insert into books_types (description) values('Estudos Obrigatório');

insert into books_types (description) values('Estudos Casual');

insert into books_types (description) values('Interesse Imediato');

insert into books_types (description) values('Interesse Casual');


insert into genres (genre) values('Administração');
insert into genres (genre) values('Adolescentes');
insert into genres (genre) values('Arte');
insert into genres (genre) values('Artesanato');
insert into genres (genre) values('Autoajuda');
insert into genres (genre) values('Aventura');
insert into genres (genre) values('Biografias');
insert into genres (genre) values('Casa');
insert into genres (genre) values('Ciências');
insert into genres (genre) values('Ciências Sociais');
insert into genres (genre) values('Cinema');
insert into genres (genre) values('Comédia');
insert into genres (genre) values('Computação');
insert into genres (genre) values('Conto');
insert into genres (genre) values('Coreano');
insert into genres (genre) values('Crônica');
insert into genres (genre) values('Culinária');
insert into genres (genre) values('Didáticos');
insert into genres (genre) values('Direito');
insert into genres (genre) values('Economia');
insert into genres (genre) values('Educação');
insert into genres (genre) values('Engenharia');
insert into genres (genre) values('Ensaio');
insert into genres (genre) values('Entretenimento');
insert into genres (genre) values('Epopéia');
insert into genres (genre) values('Erótico');
insert into genres (genre) values('Espanhol');
insert into genres (genre) values('Espiritualidade');
insert into genres (genre) values('Esportes');
insert into genres (genre) values('Estilo de Vida');
insert into genres (genre) values('Fabula');
insert into genres (genre) values('Família');
insert into genres (genre) values('Fantasia');
insert into genres (genre) values('Farsa');
insert into genres (genre) values('Ficção Científica');
insert into genres (genre) values('Filosofia');
insert into genres (genre) values('Fotografia');
insert into genres (genre) values('Francês');
insert into genres (genre) values('Gastronomia');
insert into genres (genre) values('Graphic Novels');
insert into genres (genre) values('Guias de Viagem');
insert into genres (genre) values('História');
insert into genres (genre) values('Histórias Reais');
insert into genres (genre) values('Horror');
insert into genres (genre) values('HQs');
insert into genres (genre) values('Humor');
insert into genres (genre) values('Infantil');
insert into genres (genre) values('Informática');
insert into genres (genre) values('Inglês');
insert into genres (genre) values('Italiano');
insert into genres (genre) values('Japonês');
insert into genres (genre) values('Jovens');
insert into genres (genre) values('Lazer');
insert into genres (genre) values('LGBT');
insert into genres (genre) values('Mangás');
insert into genres (genre) values('Medicina');
insert into genres (genre) values('Melodrama');
insert into genres (genre) values('Mídias Digitais');
insert into genres (genre) values('Mistério');
insert into genres (genre) values('Negócios');
insert into genres (genre) values('Novela');
insert into genres (genre) values('Outros Idiomas');
insert into genres (genre) values('Pantomima');
insert into genres (genre) values('Performance');
insert into genres (genre) values('Policial');
insert into genres (genre) values('Política');
insert into genres (genre) values('Referência');
insert into genres (genre) values('Religião');
insert into genres (genre) values('Romance');
insert into genres (genre) values('Sátira');
insert into genres (genre) values('Saúde');
insert into genres (genre) values('Suspense');
insert into genres (genre) values('Teatro');
insert into genres (genre) values('Terror');
insert into genres (genre) values('Tragédia');
insert into genres (genre) values('Tragicomédia');
insert into genres (genre) values('Transporte');
insert into genres (genre) values('Turismo');
insert into genres (genre) values('Universitário');